#
GET http://localhost:2024/api/v3/admin/hotels?hostname=openhotel.club
Content-Type: application/json
account-id: c1277daa-65a8-42fa-9c92-b47b3482deda
token: xFvr9GWOoiXerVnwkrCnhtp7VyTKWerjuPv2yABpiYSa90xa5Rr2ORmKDPUKo3cJ

###

#
GET http://localhost:2024/api/v3/admin/hotels
Content-Type: application/json
account-id: c1277daa-65a8-42fa-9c92-b47b3482deda
token: xFvr9GWOoiXerVnwkrCnhtp7VyTKWerjuPv2yABpiYSa90xa5Rr2ORmKDPUKo3cJ

###