#
POST http://localhost:2024/api/v3/admin
Content-Type: application/json
account-id:	73a5a915-c29f-4fc2-8c3b-795bc4e3885f
token: BumBh5MPRvdo0WBqA69YiFSLxQggHQxMQ6gSZuRGaWyGPun5wTpwX5

###

#
POST http://localhost:2024/api/v3/admin?accountId=c1277daa-65a8-42fa-9c92-b47b3482deda
Content-Type: application/json
account-id: c1277daa-65a8-42fa-9c92-b47b3482deda
token: xFvr9GWOoiXerVnwkrCnhtp7VyTKWerjuPv2yABpiYSa90xa5Rr2ORmKDPUKo3cJ

###
