#
POST http://localhost:2024/api/v3/admin
Content-Type: application/json
account-id:	01JMB5Q2PCQXABEKCWG6MST740
token: JzgFhmIKyTgKg0YcIVCcUaJHf4MY9l7Jb6OVy2qccsgqCZlqs9fhEO

###

#
POST http://localhost:2024/api/v3/admin?accountId=c1277daa-65a8-42fa-9c92-b47b3482deda
Content-Type: application/json
account-id: c1277daa-65a8-42fa-9c92-b47b3482deda
token: xFvr9GWOoiXerVnwkrCnhtp7VyTKWerjuPv2yABpiYSa90xa5Rr2ORmKDPUKo3cJ

###
