//ref: https://gist.github.com/rescueboy/8170278

export const LANGUAGE_LIST = [
  { name: "Spanish", code: "es" },
  { name: "English", code: "en" },
  //
  { name: "Afrikaans", code: "af" },
  { name: "Arabic", code: "ar" },
  { name: "Algerian", code: "ar-DZ" }, // Dialect of Arabic
  { name: "Aramaic", code: "arc" },
  { name: "Armenian", code: "hy" },
  { name: "Basque", code: "eu" },
  { name: "Bengali", code: "bn" },
  { name: "Bulgarian", code: "bg" },
  { name: "Berber", code: "ber" },
  { name: "Burmese", code: "my" },
  { name: "Bosnian", code: "bs" },
  { name: "Brazilian", code: "pt-BR" }, // Brazilian Portuguese
  { name: "Catalan", code: "ca" },
  { name: "Cantonese", code: "yue" },
  { name: "Croatian", code: "hr" },
  { name: "Czech", code: "cs" },
  { name: "Cypriot", code: "el-CY" }, // Greek (Cyprus)
  { name: "Corsica", code: "co" },
  { name: "Creole", code: "ht" }, // Haitian Creole
  { name: "Danish", code: "da" },
  { name: "Dutch", code: "nl" },
  { name: "Egyptian", code: "arz" }, // Egyptian Arabic
  { name: "Estonian", code: "et" },
  { name: "Finnish", code: "fi" },
  { name: "French", code: "fr" },
  { name: "Flemish", code: "nl-BE" },
  { name: "Galician", code: "gl" },
  { name: "German", code: "de" },
  { name: "Greek", code: "el" },
  { name: "Georgian", code: "ka" },
  { name: "Hebrew", code: "he" },
  { name: "Hindi", code: "hi" },
  { name: "Hungarian", code: "hu" },
  { name: "Hawaiian", code: "haw" },
  { name: "Indonesian", code: "id" },
  { name: "Italian", code: "it" },
  { name: "Inuit", code: "iu" },
  { name: "Irish", code: "ga" },
  { name: "Icelandic", code: "is" },
  { name: "Japanese", code: "ja" },
  { name: "Javanese", code: "jv" },
  { name: "Korean", code: "ko" },
  { name: "Lithuanian", code: "lt" },
  { name: "Malay", code: "ms" },
  { name: "Malayalam", code: "ml" },
  { name: "Mandarin", code: "zh" },
  { name: "Norwegian", code: "no" },
  { name: "Nepalese", code: "ne" },
  { name: "Panjabi", code: "pa" },
  { name: "Polish", code: "pl" },
  { name: "Portuguese", code: "pt" },
  { name: "Romanian", code: "ro" },
  { name: "Romani", code: "rom" },
  { name: "Russian", code: "ru" },
  { name: "Serbian", code: "sr" },
  { name: "Slovak", code: "sk" },
  { name: "Slovene", code: "sl" },
  { name: "Swedish", code: "sv" },
  { name: "Scottish", code: "gd" },
  { name: "Sanskrit", code: "sa" },
  { name: "Tamil", code: "ta" },
  { name: "Telugu", code: "te" },
  { name: "Thai", code: "th" },
  { name: "Turkish", code: "tr" },
  { name: "Tagalog", code: "tl" },
  { name: "Tahitian", code: "ty" },
  { name: "Tibetan", code: "bo" },
  { name: "Ukrainian", code: "uk" },
  { name: "Vietnamese", code: "vi" },
  { name: "Welsh", code: "cy" },
  { name: "Wu", code: "wuu" },
];
