# Login
POST http://localhost:2024/api/v2/account/login
Content-Type: application/json

{
  "ticketId": "9045fcb6-a58f-461a-9ae9-c14fc1e02290",

  "email": "pagoru@gmail.com",
  "password": "123456Abc*",
  "otpToken": "259461"
}