# Login
POST http://localhost:2024/api/v2/account/login
Content-Type: application/json

{
  "ticketId": "aa3b3fc4-3207-44dc-9f87-f0da77665240",

  "email": "pagoru@gmail.com",
  "password": "123456Abc*",
  "captchaId": "M9dSOF4OVxfCSmW1qarA7TlviHzqUaHL"
}