# Register
POST http://localhost:2024/api/v2/account/register
Content-Type: application/json

{
  "email": "pagoru@gmail.com",
  "username": "pagoru",
  "password": "123456Abc*",
  "captchaId": "SmiRZmrTJVOPVft9CzcD189PqXE9lfBQ"
}