# Get list
GET http://localhost:2024/api/v2/admin
token: x7GzeFJvLuNWUCCas2EBLB7an5rsJfpF3jOInSOG0sa17AGQAszHFwBVKsTJjWIh
sessionId: 3be671dd-bfb8-4cb0-bc68-bfe09b036f2e

###

# Add new
POST http://localhost:2024/api/v2/admin
token: dUpAHJIfu5n8MDVJasedEqfMDoqCaXRqsGNyhoEYKiR3WIM70goKHUsWkoPHmkfn
sessionId: 447321fd-361e-4697-9b36-1eba13fb16da
Content-Type: application/json

{
  "email": "pagoru@gmail.com"
}
###

# Remove new
DELETE http://localhost:2024/api/v2/admin
token: x7GzeFJvLuNWUCCas2EBLB7an5rsJfpF3jOInSOG0sa17AGQAszHFwBVKsTJjWIh
sessionId: 3be671dd-bfb8-4cb0-bc68-bfe09b036f2e
Content-Type: application/json

{
  "email": "pagoru@gmail.com"
}
###