# Claim Session
POST http://localhost:2024/api/v2/server/claim-session
Content-Type: application/json
server-id: 3bf6c370-6011-4c0e-a99d-a9ba0aad7413
token: lSW0AZBg3frHtNm12NNau7cEwvCBDk0F

{
  "ticketId": "9a17faeb-d037-4552-b9b7-35a6b8378fb6",
  "ticketKey": "THIS_IS_A_PRIVATE_TOKEN",

  "sessionId": "27b185b9-1c0a-4f0b-b3b8-ce8b73882551",
  "token": "PSMKAA2KhxuYEAUVo4frSkNqoc1eF7u1JfwpyhoNN0n02omeS4mZkAZEJdZjCxlI"
}