#
GET http://localhost:2024/api/v3/user/@me
account-id:	c1277daa-65a8-42fa-9c92-b47b3482deda
token: tpOTecDoBDyUBX5a5KR97hMk2cBnQxORVVOSx1DvrOWbrXzqMG5JrbxhycB4sTEE
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0

###

#
GET http://localhost:2024/api/v3/user/@me
connection-id: 97a59ecd-a440-4ec9-869e-0757b42bc0c2
token: 6f0m3f6sRsFx2Gt8DGblvUncZBHTeDCQsIvCOcPLgUBXj7bAgvMRrhC6Z6cYXkml
license-token: 6HuprPIVybhHSPHg#Zxrq8TA45DZZe0Z92SXHDzROrcKM6uAF

###