# Verify Session
POST http://localhost:2024/v1/hotel/verify-session
Content-Type: application/json

{
  "username": "pagoru123",
  "sessionId": "iZyHMLpYMUFVutkH",
  "token": "CnhwAZ7ZbNGfOWlhBoyNRsPD5SmDVMY8BVO2rSzFbpm9JblhsPvh73xZNUIvc2k8"
}

###